stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/raw
    - src/features/data_preprocessing.py
    outs:
    - data/processed
  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/processed
    - models/model.pkl
    - src/models/model_evaluation.py
    outs:
    - reports/run_info.json
    metrics:
    - reports/metrics.json
  model_registration:
    cmd: python src/models/model_register.py
    deps:
    - src/models/model_register.py
    - reports/run_info.json
    - reports/metrics.json
